# Reverse proxy for MP4/m3u8/ts streaming
location ~* \.(m3u8|ts)$ {

    access_by_lua_file /etc/nginx/lua/bw_check.lua;

    
    include /etc/nginx/snippets/proxy-common.conf;
    
    log_by_lua_file /etc/nginx/lua/bw_record.lua;  # runs AFTER response

    access_log /var/log/nginx/bw_debug.log bw_debug;

    # proxy_limit_rate 2m;
    # After verification we will  have capped at 1m;
    limit_rate 1536k; # 1.5 MiB/s    
}

location ~* \.(mp4)$ {

    include /etc/nginx/snippets/proxy-common.conf;

    proxy_buffering off;
    proxy_request_buffering off;

}


location / {
    default_type text/plain;
    return 404 "Not Found";
}